version: '3.8'

services:
  frontend:
    build:
      context: ./employees-dashboard
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./employees-api
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=employee-management
      - DB_LOG=false

    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=employee-management
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  automation:
    build:
      context: ./automation
      dockerfile: Dockerfile
    ports:
      - "9323:9323"
    environment:
      - HOST=http://frontend:3000

    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
